/*
 * Copyright (C) 2025 Open Source Digital Signage Initiative.
 *
 * You can redistribute it and/or modify
 * it under the terms of the Elastic License 2.0 (ELv2) as published by
 * the Search AI Company, either version 3 of the License, or
 * any later version.
 *
 * You should have received a copy of the GElastic License 2.0 (ELv2).
 * see <https://www.elastic.co/licensing/elastic-license>.
 */
import { createWorkflow, createStep } from '@mastra/core/workflows';
import { z } from 'zod';
import { logger } from '../../logger';
import { summarizeAndAnalyzeTool } from '../../tools/market-research/summarizeAndAnalyze';
import { generateChartTool, createPowerpointTool } from '../../tools/presenter';
import { parseJsonStrings } from '../../tools/xibo-agent/utility/jsonParser';
import { promises as fs } from 'fs';
import path from 'path';
import { config } from '../../tools/xibo-agent/config';

// --- Helper Functions and Schemas ---

const hexColorSchema = z.string().regex(/^#[0-9a-fA-F]{6}$/, "Must be a valid 6-digit hex color code (e.g., #RRGGBB)");

/**
 * Defines the structure for a single slide's design, as determined by the design AI.
 */
const slideDesignSchema = z.object({
  title: z.string().describe("The main title of the slide."),
  layout: z.enum(['title_slide', 'section_header', 'content_with_visual', 'content_only', 'quote'])
    .describe("The layout type for the slide."),
  bullets: z.array(z.string()).describe("A list of key bullet points for the slide."),
  visual_suggestion: z.enum(['bar_chart', 'pie_chart', 'line_chart', 'none']).describe("The suggested type of visual for the slide."),
  context_for_visual: z.string().describe("The specific topic or data context from the report needed to create the visual."),
  special_content: z.string().optional().describe("Special content for layouts like 'quote'."),
});
type SlideDesign = z.infer<typeof slideDesignSchema>;

/**
 * Defines the structure for chart data, to be generated by the analyst AI.
 */
const chartDataSchema = z.object({
    chart_type: z.enum(['bar', 'pie', 'line']),
    title: z.string(),
    labels: z.array(z.string()),
    data: z.array(z.number()),
});
type ChartData = z.infer<typeof chartDataSchema>;

const successOutputSchema = z.object({
    success: z.literal(true),
    data: z.object({
        powerpointPath: z.string(),
    }),
});
const errorOutputSchema = z.object({
    success: z.literal(false),
    message: z.string(),
});
const finalOutputSchema = z.union([successOutputSchema, errorOutputSchema]);


// --- Workflow Definition ---

/**
 * @workflow intelligent-presenter-workflow
 * This workflow automates the creation of a PowerPoint presentation from a given markdown report.
 * It follows a multi-step process involving several AI agents:
 * 1. Read Report: Reads the source markdown file.
 * 2. Design Presentation: An AI designs the slide structure and theme.
 * 3. Generate Title Image: An AI generates a background image for the title slide.
 * 4. Generate Content: AIs generate speech notes and data for charts.
 * 5. Generate Visuals: The system creates chart images from the data.
 * 6. Assemble Outputs: All components are combined into a final .pptx file.
 */
export const intelligentPresenterWorkflow = createWorkflow({
  id: 'intelligent-presenter-workflow',
  description: 'Generates a PowerPoint presentation with speaker notes from a markdown report file.',
  inputSchema: z.object({
    reportFileName: z.string().describe('The name of the report file located in persistent_data/reports.'),
    fileNameBase: z.string().optional().describe('The base name for the output files. Defaults to the report file name.'),
  }),
  outputSchema: finalOutputSchema,
})
.then(createStep({
    /**
     * @step read-report-file
     * Reads the content of the specified report file from the 'reports' directory.
     * If the file cannot be read, it forwards an error message to the next step.
     */
    id: 'read-report-file',
    inputSchema: z.object({
        reportFileName: z.string(),
        fileNameBase: z.string().optional(),
    }),
    outputSchema: z.object({
        reportContent: z.string(),
        fileNameBase: z.string(),
        errorMessage: z.string().optional(),
    }),
    execute: async (params) => {
        const { reportFileName, fileNameBase } = params.inputData;
        const resolvedFileNameBase = fileNameBase || path.parse(reportFileName).name;
        const filePath = path.join(config.reportsDir, reportFileName);
        logger.info({ filePath, resolvedFileNameBase }, "📄 Reading report file...");
        
        try {
            await fs.access(filePath);
            const reportContent = await fs.readFile(filePath, 'utf-8');
            return { reportContent, fileNameBase: resolvedFileNameBase };
        } catch (error) {
            const message = `Report file not found or could not be read: ${filePath}`;
            logger.error({ filePath, error }, message);
            return { reportContent: '', fileNameBase: resolvedFileNameBase, errorMessage: message };
        }
    },
}))
.then(createStep({
    /**
     * @step design-presentation
     * Uses an AI to analyze the report content and design the presentation structure.
     * It defines the layout, title, and visual suggestions for each slide, plus a theme.
     * It includes robust parsing to handle various formats of AI-generated JSON.
     */
    id: 'design-presentation',
    inputSchema: z.object({
        reportContent: z.string(),
        fileNameBase: z.string(),
        errorMessage: z.string().optional(),
    }),
    outputSchema: z.object({
        presentationDesign: z.array(slideDesignSchema),
        reportContent: z.string(),
        fileNameBase: z.string(),
        themeColor1: z.string().describe("The primary theme color for the presentation background gradient."),
        themeColor2: z.string().describe("The secondary theme color for the presentation background gradient."),
        errorMessage: z.string().optional(),
    }),
    execute: async (params) => {
        const { reportContent, fileNameBase, errorMessage } = params.inputData;
        if (errorMessage) {
            return { presentationDesign: [], reportContent, fileNameBase, errorMessage, themeColor1: '#F1F1F1', themeColor2: '#CCCCCC' };
        }
        
        logger.info("🤖 [Designer AI] Analyzing report and designing presentation structure...");
        let designResult;
        try {
            // Prompt for the Designer AI to create the presentation structure and theme.
            const prompt = `あなたは一流のプレゼンテーション設計者です。以下のレポートを分析し、最適なプレゼン構成案とテーマカラーをJSONで出力してください。
            返却するJSONは、必ず以下のキーを持つオブジェクトです:
            - "theme_colors": { "color1": "#HEXCODE", "color2": "#HEXCODE" } (レポートの雰囲気に合うグラデーション用のテーマカラー2色。必ず6桁の16進数カラーコードで指定してください)
            - "slides": array (スライド構成案の配列)

            スライド構成案の各配列要素は、以下のキーを持つJSONオブジェクトです:
            - "title": string (スライドのタイトル)
            - "layout": 'title_slide' | 'section_header' | 'content_with_visual' | 'content_only' | 'quote' (スライドの役割に応じたレイアウトタイプ)
            - "bullets": string[] (スライドの要点を箇条書きで)
            - "visual_suggestion": 'bar_chart' | 'pie_chart' | 'line_chart' | 'none' (グラフの提案、不要なら'none')
            - "context_for_visual": string (グラフ作成に必要な文脈)
            - "special_content": string (任意。引用レイアウトの場合の引用文など)
            
            最初のスライドは必ず layout: 'title_slide' にし、途中に区切りとして layout: 'section_header' を適切に配置してください。
            --- レポート ---
            ${reportContent}`;
            
            designResult = await summarizeAndAnalyzeTool.execute({ ...params, context: { 
                text: reportContent, 
                objective: prompt,
                temperature: 0.3, // Lower temperature for more deterministic structure
                topP: 0.9,
            } });
            if (!designResult.success) {
                const message = `Designer AI failed: ${designResult.message}`;
                logger.error({ error: designResult.message }, message);
                return { presentationDesign: [], reportContent, fileNameBase, errorMessage: message, themeColor1: '#F1F1F1', themeColor2: '#CCCCCC' };
            }

            const designData = parseJsonStrings(designResult.data.summary);
            if (!designData) {
                const message = "Failed to parse presentation design JSON from AI.";
                logger.error({ aiOutput: designResult.data.summary }, message);
                return { presentationDesign: [], reportContent, fileNameBase, errorMessage: message, themeColor1: '#F1F1F1', themeColor2: '#CCCCCC' };
            }

            // --- Robust AI Response Parsing ---
            // The AI might return JSON in slightly different formats, so we try multiple schemas.
            const expectedObjectSchema = z.object({
                theme_colors: z.object({ color1: hexColorSchema, color2: hexColorSchema }),
                slides: z.array(slideDesignSchema),
            });
            const arrayOnlySchema = z.array(slideDesignSchema);

            // 1. Try parsing the expected object format: { theme_colors: ..., slides: [...] }
            let objectParseResult = expectedObjectSchema.safeParse(designData);
            if (objectParseResult.success) {
                const { slides, theme_colors } = objectParseResult.data;
                return { presentationDesign: slides, reportContent, fileNameBase, themeColor1: theme_colors.color1, themeColor2: theme_colors.color2 };
            }

            // 2. Try parsing a direct array of slides (if theme is missing).
            let arrayParseResult = arrayOnlySchema.safeParse(designData);
            if (arrayParseResult.success) {
                logger.warn("AI returned an array instead of an object. Using default theme colors.");
                return { presentationDesign: arrayParseResult.data, reportContent, fileNameBase, themeColor1: '#F1F1F1', themeColor2: '#CCCCCC' };
            }
            
            // 3. Try parsing a wrapped array, e.g., { "slides": [...] }.
            if (!Array.isArray(designData) && typeof designData === 'object' && designData !== null) {
                const keys = Object.keys(designData);
                if (keys.length === 1 && Array.isArray(designData[keys[0]])) {
                    const wrappedArray = designData[keys[0]];
                    let wrappedArrayParseResult = arrayOnlySchema.safeParse(wrappedArray);
                    if (wrappedArrayParseResult.success) {
                        logger.warn("AI returned a wrapped array. Extracting array and using default theme colors.");
                        return { presentationDesign: wrappedArrayParseResult.data, reportContent, fileNameBase, themeColor1: '#F1F1F1', themeColor2: '#CCCCCC' };
                    }
                }
            }

            // If all parsing attempts fail, forward an error.
            const message = `AI output did not match any expected schema. Zod error: ${objectParseResult.error.message}`;
            logger.error({ error: objectParseResult.error, aiOutput: designData }, message);
            return { presentationDesign: [], reportContent, fileNameBase, errorMessage: message, themeColor1: '#F1F1F1', themeColor2: '#CCCCCC' };

        } catch (error) {
            const message = error instanceof Error ? error.message : "An unknown error occurred during presentation design.";
            logger.error({ error, aiOutput: (designResult && designResult.success) ? designResult.data.summary : 'AI output not available.' }, message);
            return { presentationDesign: [], reportContent, fileNameBase, errorMessage: message, themeColor1: '#F1F1F1', themeColor2: '#CCCCCC' };
        }
    },
}))
.then(createStep({
    /**
     * @step generate-title-image
     * Generates a background image for the title slide based on its title.
     * This step is optional; if it fails, the workflow continues without a title image.
     */
    id: 'generate-title-image',
    inputSchema: z.object({
        presentationDesign: z.array(slideDesignSchema),
        reportContent: z.string(),
        fileNameBase: z.string(),
        themeColor1: z.string(),
        themeColor2: z.string(),
        errorMessage: z.string().optional(),
    }),
    outputSchema: z.object({
        presentationDesign: z.array(slideDesignSchema),
        reportContent: z.string(),
        fileNameBase: z.string(),
        themeColor1: z.string(),
        themeColor2: z.string(),
        titleSlideImagePath: z.string().optional(),
        titleSlideImageBuffer: z.any().optional(),
        errorMessage: z.string().optional(),
    }),
    execute: async (params) => {
        const { presentationDesign, reportContent, fileNameBase, errorMessage, themeColor1, themeColor2 } = params.inputData;
        if (errorMessage || presentationDesign.length === 0) {
            return { ...params.inputData, titleSlideImagePath: undefined };
        }
        
        const titleSlide = presentationDesign[0];
        // We only generate an image for the title slide.
        if (titleSlide.layout !== 'title_slide') {
            return { ...params.inputData, titleSlideImagePath: undefined };
        }

        logger.info("🎨 [Image Generator] Generating background image for the title slide...");

        try {
            // Step 1: Use an AI to distill the title into visual keywords.
            // This prevents the image generator from trying to render the literal title text.
            const keywordExtractionPrompt = `From the following presentation title, extract 5-7 core visual keywords suitable for generating an abstract background image. The keywords should focus on concepts, themes, and colors. Do not include the original title text. Output only a comma-separated list. Title: "${titleSlide.title}"`;

            const keywordResult = await summarizeAndAnalyzeTool.execute({
                ...params,
                context: {
                    text: titleSlide.title,
                    objective: keywordExtractionPrompt,
                    temperature: 0.2, // Low temperature for precise keyword extraction
                    topP: 0.9,
                }
            });

            if (!keywordResult.success) {
                logger.warn("Failed to extract keywords for title image. Skipping image generation.");
                return { ...params.inputData, titleSlideImagePath: undefined };
            }

            const keywords = keywordResult.data.summary.trim();
            logger.info({ keywords }, "Extracted keywords for title image.");

            // Step 2: Generate an image using only the distilled keywords.
            const prompt = `An abstract, professional background image representing the following themes: ${keywords}. High resolution, clean, and visually appealing.`;
            const negativePrompt = 'text, words, letters, numbers, writing, typography, signatures, logos, people, faces';

            const { generateImage } = await import('../../tools/xibo-agent/generateImage/imageGeneration');
            const imageResult = await generateImage.execute({
                ...params,
                context: {
                    prompt,
                    aspectRatio: '16:9',
                    negativePrompt,
                    returnBuffer: true,
                },
            });

            if (imageResult.success && imageResult.data) {
                const d: any = imageResult.data as any;
                if (d.buffer) {
                    return { ...params.inputData, titleSlideImageBuffer: d.buffer, titleSlideImagePath: undefined };
                }
                if (d.imagePath) {
                    return { ...params.inputData, titleSlideImagePath: d.imagePath };
                }
            }
            logger.warn(`Failed to generate title slide image. error=${(imageResult as any).message ?? ''}`);
            return { ...params.inputData, titleSlideImagePath: undefined };
        } catch (error) {
            const message = error instanceof Error ? error.message : "An unknown error occurred during title image generation.";
            logger.error({ error }, message);
            // Don't propagate this as a workflow-stopping error. Just proceed without the image.
            return { ...params.inputData, titleSlideImagePath: undefined };
        }
    },
}))
.then(createStep({
    /**
     * @step generate-content
     * Enriches the presentation design with actual content. For each slide, it:
     * 1. Generates a speech script using an AI.
     * 2. If a visual is suggested, uses an AI to extract or create data for a chart.
     * These operations are run in parallel for efficiency.
     */
    id: 'generate-content',
    inputSchema: z.object({
        presentationDesign: z.array(slideDesignSchema),
        reportContent: z.string(),
        fileNameBase: z.string(),
        themeColor1: z.string(),
        themeColor2: z.string(),
        titleSlideImagePath: z.string().optional(),
        titleSlideImageBuffer: z.any().optional(),
        errorMessage: z.string().optional(),
    }),
    outputSchema: z.object({
        enrichedSlides: z.array(z.object({
            design: slideDesignSchema,
            chartData: chartDataSchema.nullable(),
            speech: z.string(),
        })),
        fileNameBase: z.string(),
        themeColor1: z.string(),
        themeColor2: z.string(),
        titleSlideImagePath: z.string().optional(),
        titleSlideImageBuffer: z.any().optional(),
        errorMessage: z.string().optional(),
    }),
    execute: async (params) => {
        const { presentationDesign, reportContent, fileNameBase, errorMessage, themeColor1, themeColor2, titleSlideImagePath, titleSlideImageBuffer } = params.inputData;
        if (errorMessage) {
            return { enrichedSlides: [], fileNameBase, errorMessage, themeColor1, themeColor2, titleSlideImagePath, titleSlideImageBuffer };
        }

        logger.info("✍️ [Analyst & Speechwriter AIs] Generating content in batch...");
        const slidesInput = presentationDesign.map((s, idx) => ({
            idx,
            title: s.title,
            bullets: s.bullets,
            visual_suggestion: s.visual_suggestion,
            context_for_visual: s.context_for_visual,
        }));

        const batchObjective = `You are a presentation content generator. Given an array of slides and the report body, output a JSON object strictly in the following format (no extra commentary):
{
  "slides": [
    { "idx": number, "speech": string, "chartData": null | { "chart_type": "bar"|"pie"|"line", "title": string, "labels": string[], "data": number[] } }
  ]
}
Rules:
- The speech should be ~150 Japanese characters, readable and presenter-friendly. Do not include markdown fences.
- If a slide's visual_suggestion is 'none', set chartData to null.
- If chartData is provided, labels.length must equal data.length and data values must be numbers.
- Use the slide's context_for_visual only when chartData is required.
`;

        const combined = `# Slides\n\n${JSON.stringify(slidesInput, null, 2)}\n\n# Report\n\n${reportContent}`;
        const batchRes = await summarizeAndAnalyzeTool.execute({ ...params, context: { text: combined, objective: batchObjective, temperature: 0.4, topP: 0.9 } });

        let idxToResult = new Map<number, { speech: string; chartData: any | null }>();
        if (batchRes.success) {
            const parsed = parseJsonStrings(batchRes.data.summary) as any;
            const arr = Array.isArray(parsed?.slides) ? parsed.slides : [];
            for (const it of arr) {
                const i = Number(it?.idx);
                if (!Number.isFinite(i)) continue;
                const rawSpeech = typeof it?.speech === 'string' ? it.speech : '';
                const speech = rawSpeech.trim().replace(/([。\.])/g, '$1\n');
                let chartData: ChartData | null = null;
                if (it?.chartData && typeof it.chartData === 'object' && it.chartData !== null) {
                    try {
                        chartData = chartDataSchema.parse(it.chartData);
                    } catch { chartData = null; }
                }
                idxToResult.set(i, { speech: speech || '（原稿の生成に失敗しました）', chartData });
            }
        } else {
            logger.warn('Batch generation failed; falling back to empty results.');
        }

        const enrichedSlides = presentationDesign.map((design, idx) => {
            const got = idxToResult.get(idx);
            const speech = got?.speech || '（原稿の生成に失敗しました）';
            let chartData: ChartData | null = null;
            if (design.visual_suggestion !== 'none') {
                chartData = got?.chartData || null;
            }
            return { design, chartData, speech };
        });

        return { enrichedSlides, fileNameBase, themeColor1, themeColor2, titleSlideImagePath, titleSlideImageBuffer };
    },
}))
.then(createStep({
    /**
     * @step generate-visuals
     * Creates PNG images for any charts defined in the previous step.
     * It also includes fallback logic: if a slide is supposed to have a visual but
     * chart generation fails, it changes the slide's layout to 'content_only'
     * to avoid an empty space in the presentation.
     */
    id: 'generate-visuals',
    inputSchema: z.object({
        enrichedSlides: z.array(z.object({
            design: slideDesignSchema,
            chartData: chartDataSchema.nullable(),
            speech: z.string(),
        })),
        fileNameBase: z.string(),
        themeColor1: z.string(),
        themeColor2: z.string(),
        titleSlideImagePath: z.string().optional(),
        titleSlideImageBuffer: z.any().optional(),
        errorMessage: z.string().optional(),
    }),
    outputSchema: z.object({
        finalSlides: z.array(z.object({
            title: z.string(),
            bullets: z.array(z.string()),
            imagePath: z.string().optional(),
            notes: z.string(),
            layout: z.enum(['title_slide', 'section_header', 'content_with_visual', 'content_only', 'quote']),
            special_content: z.string().optional(),
        })),
        fileNameBase: z.string(),
        themeColor1: z.string(),
        themeColor2: z.string(),
        titleSlideImagePath: z.string().optional(),
        errorMessage: z.string().optional(),
    }),
    execute: async (params) => {
        const { enrichedSlides, fileNameBase, errorMessage, themeColor1, themeColor2, titleSlideImagePath } = params.inputData;
        if (errorMessage) {
            return { finalSlides: [], fileNameBase, errorMessage, themeColor1, themeColor2, titleSlideImagePath };
        }

        logger.info("🖼️ [Chart Generator] Creating chart images...");
        const finalSlidesPromises = enrichedSlides.map(async (slide, index) => {
            let imagePath: string | undefined = undefined;
            let imageBuffer: Buffer | undefined = undefined;
            // Attempt to generate a chart if data is present
            if (slide.chartData) {
                const { chart_type, ...restOfChartData } = slide.chartData;
                const chartResult = await generateChartTool.execute({ ...params, context: { ...restOfChartData, chartType: chart_type, fileName: `chart_${fileNameBase}_${index}`, returnBuffer: true }});
                if (chartResult.success) {
                    const d: any = chartResult.data as any;
                    if (d?.buffer) {
                        imageBuffer = d.buffer as Buffer;
                    } else if (d?.imagePath) {
                        imagePath = d.imagePath as string;
                    }
                } else {
                    logger.warn({ slideTitle: slide.design.title }, "Chart generation failed, proceeding without an image.");
                }
            }

            // Fallback logic: If layout requires a visual but we don't have one, change layout.
            let finalLayout = slide.design.layout;
            if (finalLayout === 'content_with_visual' && !imagePath) {
                logger.info({ slideTitle: slide.design.title }, "Visual not available for 'content_with_visual' layout. Switching to 'content_only'.");
                finalLayout = 'content_only';
            }

            return {
                title: slide.design.title,
                bullets: slide.design.bullets,
                imagePath: imagePath,
                notes: slide.speech,
                layout: finalLayout,
                special_content: slide.design.special_content,
                // Non-schema field for buffer-based images (consumed by createPowerpointTool if supported)
                ...(imageBuffer ? { imageBuffer } : {}),
            };
        });

        const finalSlides = await Promise.all(finalSlidesPromises);
        return { finalSlides, fileNameBase, themeColor1, themeColor2, titleSlideImagePath };
    },
}))
.then(createStep({
    /**
     * @step assemble-outputs
     * Takes all the generated components (slide designs, text, image paths)
     * and uses the `createPowerpointTool` to assemble the final .pptx file.
     */
    id: 'assemble-outputs',
    inputSchema: z.object({
        finalSlides: z.array(z.object({
            title: z.string(),
            bullets: z.array(z.string()),
            imagePath: z.string().optional(),
            notes: z.string(),
            layout: z.enum(['title_slide', 'section_header', 'content_with_visual', 'content_only', 'quote']),
            special_content: z.string().optional(),
        })),
        fileNameBase: z.string(),
        themeColor1: z.string(),
        themeColor2: z.string(),
        titleSlideImagePath: z.string().optional(),
        errorMessage: z.string().optional(),
    }),
    outputSchema: finalOutputSchema,
    execute: async (params) => {
        const { finalSlides, fileNameBase, errorMessage, themeColor1, themeColor2, titleSlideImagePath } = params.inputData;
        if (errorMessage) {
            return { success: false, message: errorMessage } as const;
        }

        logger.info("📦 [Assembler] Creating final PowerPoint file with notes...");
        const pptResult = await createPowerpointTool.execute({ ...params, context: { 
            fileName: fileNameBase,
            slides: finalSlides,
            themeColor1,
            themeColor2,
            titleSlideImagePath,
        }});

        if (!pptResult.success) {
            return { success: false, message: `Failed to assemble final PowerPoint file: ${pptResult.message}` } as const;
        }

        return {
            success: true,
            data: {
                powerpointPath: pptResult.data.filePath,
            },
        } as const;
    },
}))
.commit();